### ISSUE TITLE
TraceEvent looses argument names 

### ISSUE THREAD

**Issue by chrisjowen** [tomtom-international/kotlin-tools#33]
Hi Guys, 

Thanks for picking up the suggestions I made before regarding `TraceDiagnosticContext` one other thing that is useful for me is to know the argument names at the point that the `TraceEvent` is created. 

Currently `TraceEvent` simply stores the args as `val args: Array<Any?>` here https://github.com/tomtom-international/kotlin-tools/blob/master/traceevents/src/main/java/com/tomtom/kotlin/traceevents/TraceEvent.kt#L43. 

But at this point we have the method informaiton so I wonder was it a consious choice not to keep the method property names in the event? For me this is useful informaiton and currently I simply provide one argument to each trace event which encapsulates everything in a data class so I can maintain the property names. 

For my case it would be preferable if the arguments were just captured as `Map<String, Any?>`. Not sure if this is something you guys would consider else Ill just be hacking it in my side :). 

Chris

**Comment by RijnBuve-TomTom** [comment]
The primary reasons for `args` to be stored as an array is that it is stored exactly as it is obtained from the `invoke` method, without transformation. We avoid converting it  into a map or list, which is rather expensive if you generate loads of events.
Perhaps for generic consumer only this would be a useful addition, although it does make the consumer sensitive to parameter name changes, which may be more common than parameter ordering changes. Let me think about it - it should not affect performance too much, specifically not for non-generic trace event consumers.

**Comment by RijnBuve-TomTom** [comment]
Will be provided in 1.5.1 release.

**Comment by chrisjowen** [comment]
I completely understand what you mean in the issue about not wanting to generate the map each call and caching the function params (as you have done in the PR) seems a perfect solution so I'm totally happy with this. 

Thanks again for been so responsive, seems like you guys at tom-tom are doing some good things.

**Comment by rijnb** [comment]
Fixed in 1.5.1 - available on Maven Central per 2021-09-29.
